[package]
name = "hirust-auth"
authors = ["dengpju"]
version = "0.1.4"
edition = "2024"
description = "A Rust Auth"
license = "MIT"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_derive = "1.0.219"